### ISSUE TITLE
Seems to connect but providing no data

### ISSUE THREAD

**Issue by j1mco** [scooter1556/hass-addons#1]
MQTT found in this Home Assistance instance.
Starting glow2mqtt.py...
Configuring Home Assistant...
MQTT connected...
Connected to Glow MQTT broker...

[https://dean.so/wp-content/uploads/2022/04/Screenshot-from-2022-04-17-18-03-18.png](https://dean.so/wp-content/uploads/2022/04/Screenshot-from-2022-04-17-18-03-18.png)

This is what was supplied by Hildebrand:
mosquitto_sub --cafile /usr/local/etc/openssl/cert.pem -h  glowmqtt.energyhive.com -u brightuser -P brightpass -t SMART/HILD/XXXXXXXXXXXX -p 8883

**Comment by scooter1556** [comment]
Hi @j1mco,

Have you tried connecting with an mqtt client to check data is flowing for your device? If you use port 1883 instead of 8883 you don't need the certificate. 

Make sure to use the device ID of your glow display/stick and not your meter. You can confirm this in the Bright app under 'Devices'.

**Comment by j1mco** [comment]
Just checked with MQTT explorer, it's logging in fine with both 1883 and 8883, but not seeing any data published.  I've checked it's the device ID of the glow display - cheers!

**Comment by scooter1556** [comment]
Thanks for checking @j1mco . It might take a day or so for data to start flowing but the next step would be to get Hildebrand to double-check everything has been enabled correctly on their end for MQTT access. I assume the Bright app is showing data every 10 seconds as it should?

**Comment by j1mco** [comment]
It's been a few days and everything is working in Bright as it should so I've emailed them thanks

**Comment by j1mco** [comment]
Fixed - was indeed an issue on the server side.  The MQTT hadn't been enabled correctly.
