### ISSUE TITLE
OSError: [Errno 99] Address not available

### ISSUE THREAD

**Issue by snigehere** [scooter1556/hass-addons#2]
I am new to home assistant so this may be my issue rather than the add on.  When I start the addon I see the following in the log ... I am unsure why I would get an OS error on the address

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
MQTT found in this Home Assistant instance.
Starting ginlong-wifi-mqtt.py...
Configuring Home Assistant...
Traceback (most recent call last):
  File "/ginlong-wifi-mqtt.py", line 108, in <module>
    sock.bind((listen_address, listen_port))
OSError: [Errno 99] Address not available
[cmd] /run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`

I have the Listen address set to 192.168.0.249 and the port 9999 .. I have set up server b in the data stick and added the ha server ip - both are fixed IP addresses (the data stick configured as fixed, the ha server as reserved). I am able to logon to the data logger with the browser.

I am running HA in a virtual box under windows

**Comment by scooter1556** [comment]
Hi @snigehere ,

It sounds like you have setup your data stick correctly so it will broadcast data over UDP to your HA instance however try setting the listen address in the plugin to 0.0.0.0

**Comment by snigehere** [comment]
Hi - thanks for the update  .. I changed the listener to 0.0.0.0 and no longer get the OSError message (still no data but no error now).

**Comment by scooter1556** [comment]
The stick should send data to the registered servers every 6 minutes by default. Make sure it has been rebooted since adding your HA IP and port!

**Comment by scooter1556** [comment]
A couple more things to check:

- In Advanced -> working mode I have it set to ''Data Collection'
- Server B I have setup with a blank domain and connection set to TCP. There is also a test button if you want to check it is managing to send data to the plugins TCP listener.

Failing that it might be that you are using a version of the stick or firmware not supported. I only have my setup for testing but I know there are many variants which all send a different identifier code and data payload.

For reference the firmware version of my stick is: H4.01.44Y4.0.01W1.0.19(2014-11-101)

**Comment by snigehere** [comment]
Thanks - I will set some time aside to investigate some more ... I don't have an advanced option nor a test button
The stick is a wifi version (I know there are 3 types of stick - lan, wifi and gsm) and the firmware version is shown as MW_08_0501_1.58.  I found another post on the web that gave a hidden config pages (http://<IP Address>/config_hide.html where I can find "working mode" and it is set to "data collection"
![solis stick 1](https://user-images.githubusercontent.com/104912027/167634415-9db6dd0c-ecd1-44e5-a9b0-4ee0c0340e19.jpg)
![solis stick 2](https://user-images.githubusercontent.com/104912027/167634420-668600ce-f6b3-4f75-98a3-b2037d344396.jpg)
![solis stick 3](https://user-images.githubusercontent.com/104912027/167634424-8be2ea1e-4862-41b6-9e0c-d4b106bf30b3.jpg)

**Comment by scooter1556** [comment]
It looks like you are using a new Solis 4G inverter judging by the FW. Things started to get tricky with these because the data payload changed with every firmware release so each one needed reverse engineering.

There is a script here which claims to be written for your particular firmware so might be worth trying: [https://github.com/codeworkx/ginlong-mqtt](https://github.com/codeworkx/ginlong-mqtt)

If this works I can try to integrate additional support into the plugin but it will be trial and error given I have nothing here to test unless I can get a binary dump of the TCP messages being sent by the inverter and data logger (the newer data loggers send various types of message I believe, not just inverter updates).

**Comment by snigehere** [comment]
Thanks for the link - I will have a look and see if I can get it working.  So far I have just used the GUI part of home assistant and not gone any deeper so I have a steep learning curve ahead - my last coding role was 20 years ago and with lotus script!  I maybe some time before I get back.

**Comment by scooter1556** [comment]
@snigehere , no problem, have fun! :+1:

**Comment by snigehere** [comment]
So just to update ... I found another post that suggested looking at <IP>/status.html  .. looking at the page source I can see all the data I need to get out .... Leaving off the style definitions at the top of the page this is the content ... I don't know if its of interest or not  .... so far I have not seen any data coming showing up in the mqtt broker.  
One person commented that the server b does not work on the latest microcode so suggested altering the alternate one for the ginlong cloud in the config_hide.html page but not sure if that will work or will only kick in if the primary cloud fails ...  some more testing once the sun comes up again.

I guess one option would be to keep refreshing the status page and scaping the content from the page.  I would need to check if I can send the login in the page request.

`<script type="text/javascript">
var webdata_sn = "163AF1215190123 ";
var webdata_msvn = "0048";
var webdata_ssvn = "002B";
var webdata_pv_type = "00AF";
var webdata_rate_p = "";
var webdata_now_p = "20";
var webdata_today_e = "52.70";
var webdata_total_e = "773.0";
var webdata_alarm = "";
var webdata_utime = "1";
var cover_mid = "717955894";
var cover_ver = "MW_08_0501_1.58";
var cover_wmode = "STA";
var cover_ap_ssid = "AP_717955894";
var cover_ap_ip = "10.10.100.254";
var cover_ap_mac = "98D863E48B3D";
var cover_sta_ssid = "nandf-home";
var cover_sta_rssi = "100%";
var cover_sta_ip = "192.168.0.249";
var cover_sta_mac = "98D863E48B3C";
var status_a = "1";
var status_b = "0";
var status_c = "0";

function initPageText(){var list=window.parent.reList("status");fileText("st1",list["t1"]);fileText("st2",list["t2"]);fileText("st3",list["t3"]);for(var i=1;i<=27;i++){if(i!=14){fileText("tx"+i,list[i])}}changeFont();child_getH()}function upfold(v){if(document.getElementById("up_"+v+"_div").style.display=="none"){show("up_"+v+"_div");reCon("p_"+v).innerHTML="-"}else{hide("up_"+v+"_div");reCon("p_"+v).innerHTML="+"}}function init_main_page(){var on=window.parent.reTip("1");var off=window.parent.reTip("2");document.getElementById("cover_mid").innerHTML=cover_mid;document.getElementById("cover_ver").innerHTML=cover_ver;document.getElementById("cover_ap_status").innerHTML=off;document.getElementById("cover_sta_status").innerHTML=off;if(cover_wmode!="STA"){document.getElementById("cover_ap_status").innerHTML=on;document.getElementById("cover_ap_ssid").innerHTML=cover_ap_ssid;document.getElementById("cover_ap_ip").innerHTML=cover_ap_ip;document.getElementById("cover_ap_mac").innerHTML=cover_ap_mac}if(cover_wmode!="AP"){document.getElementById("cover_sta_status").innerHTML=on;document.getElementById("cover_sta_ssid").innerHTML=cover_sta_ssid;document.getElementById("cover_sta_rssi").innerHTML=cover_sta_rssi;document.getElementById("cover_sta_ip").innerHTML=cover_sta_ip;document.getElementById("cover_sta_mac").innerHTML=cover_sta_mac}if(webdata_sn==""){webdata_sn="---"}fileText("webdata_sn",webdata_sn);if(webdata_msvn==""){webdata_msvn="---"}fileText("webdata_msvn",webdata_msvn);if(webdata_ssvn==""){webdata_ssvn="---"}fileText("webdata_ssvn",webdata_ssvn);if(webdata_pv_type==""){webdata_pv_type="---"}fileText("webdata_pv_type",webdata_pv_type);if(webdata_rate_p==""){webdata_rate_p="---"}fileText("webdata_rate_p",webdata_rate_p+" W");if(webdata_now_p==""||webdata_now_p==0){webdata_now_p="---"}fileText("webdata_now_p",webdata_now_p+" W");if(webdata_today_e==""){webdata_today_e="---"}fileText("webdata_today_e",webdata_today_e+" kWh");if(webdata_total_e==""){webdata_total_e="---"}fileText("webdata_total_e",webdata_total_e+" kWh");if(webdata_alarm==""){webdata_alarm="---"}fileText("webdata_alarm",webdata_alarm);if(webdata_utime==""){if(document.getElementById("webdata_sn").innerHTML=="---"){webdata_utime="---"}else{webdata_utime=value+window.parent.reTip("5")}}fileText("webdata_utime",webdata_utime);var st_en=window.parent.reTip("3");var st_dis=window.parent.reTip("4");var st_un=window.parent.reTip("41");if(status_a=="1"){document.getElementById("cover_remote_status_a").innerHTML=st_en}else{if(status_a=="0"){document.getElementById("cover_remote_status_a").innerHTML=st_dis}else{document.getElementById("cover_remote_status_a").innerHTML=st_un}}if(status_b=="1"){document.getElementById("cover_remote_status_b").innerHTML=st_en}else{if(status_b=="0"){document.getElementById("cover_remote_status_b").innerHTML=st_dis}else{document.getElementById("cover_remote_status_b").innerHTML=st_un}}};

</script>`

**Comment by scooter1556** [comment]
@snigehere thanks for the update.

Scraping the status.html page is definitely one way of getting the data although plagued by the same inconsistencies between firmware as the TCP data with the added complication that the wifi stick isn't publishing the data to a TCP server lying in wait, instead we have a piece of code polling the web page including during night time hours when it won't be available leading to lots of timeouts. It will always be preferable to process the TCP packet sent from the wifi stick but that does involve some reverse engineering of the data packet to understand it.
