### ISSUE TITLE
Error starting glow2mqtt.py

### ISSUE THREAD

**Issue by Adoruta** [scooter1556/hass-addons#3]
Since v1.1.2, error starting glow2mqtt.py:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Using external MQTT broker.
parse error: Expected string key before ':' at line 1, column 4
[05:40:25] ERROR: Unknown HTTP error occured
Starting glow2mqtt.py...
usage: glow2mqtt.py [-h] [--glow_provider GLOW_PROVIDER] --glow_device
                    GLOW_DEVICE --glow_username GLOW_USERNAME --glow_password
                    GLOW_PASSWORD [--mqtt_address MQTT_ADDRESS]
                    [--mqtt_port MQTT_PORT] [--mqtt_username MQTT_USERNAME]
                    [--mqtt_password MQTT_PASSWORD] [--homeassistant]
                    [--debug]
glow2mqtt.py: error: argument --mqtt_port: invalid int value: 'null'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

I should be using the internal MQTT broker.

**Comment by scooter1556** [comment]
Hi @Adoruta , I'm aware of the issue. There have been changes to the addon base image which seems to have messed up mqtt service detection. I'm looking into it now.

Thanks.

**Comment by snigehere** [comment]
Same issue for me Scott .. I have subscribed to this issue so I can see any updates

**Comment by scooter1556** [comment]
This should be fixed now with version 1.1.3. Please check for updates in your install.

Apologies for the issues.

**Comment by Adoruta** [comment]
Perfect. Working again. Thanks.

**Comment by snigehere** [comment]
Working again - thanks for the quick reaction to the issue
