### ISSUE TITLE
gas_meter has unit kWh which is unsupported for device_class gas

### ISSUE THREAD

**Issue by snigehere** [scooter1556/hass-addons#4]
Just installed 1.2.0 and see an error in the log for unit of measure - I am unsure if this was there before as I don't have the prior logs (2 updates today)

2022-08-16 11:20:10.064 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.glow_441793525f6c_gas_meter has unit kWh which is unsupported for device_class gas

**Comment by scooter1556** [comment]
@snigehere , it sounds like perhaps you are on an older version of Home Assistant? Support for gas in kWh was added a few releases back. I recently updated the code to auto-detect what units are being used to report gas as many people indicated it was showing up as m3 but actually reporting in kWh which seems to be more the norm now for the Glow APIs.

**Comment by snigehere** [comment]
Hi Scott.. no.. I am on HA 2022.8.5
![Screenshot_20220816-181246_Home Assistant](https://user-images.githubusercontent.com/104912027/184939162-cfcd596c-ac1d-42d2-966c-7f79b74fd6be.jpg)
That was the other update I installed earlier today.. I normally do updates once a week and am, I think, all up to date.

**Comment by scooter1556** [comment]
Ah, I see now that device_class gas can only take m3 or ft3 but a gas source with device_class energy in kWh is also supported in the energy dashboard. I will push out a fix ASAP.

**Comment by snigehere** [comment]
Many thanks

**Comment by snigehere** [comment]
Hi Scott .. I see you rolled a new version which I installed so my current version: 1.2.1 ... not sure if this was supposed to solve the issue.

I just upgraded HA OS from 8.2 to 8.4 so checked the log and unfortunately the unit of measure issue is not solved

2022-08-18 20:10:14.446 WARNING (Recorder) [homeassistant.components.sensor.recorder] sensor.glow_441793525f6c_gas_meter has unit kWh which is unsupported for device_class gas

Just for info my system config is now 

Home Assistant 2022.8.6
Supervisor 2022.08.3
Operating System 8.4
Frontend 20220802.0 - latest

Is there some additional detail I can provide to help debug this?

Nigel

**Comment by snigehere** [comment]
Just to add ... my energy dashboard shows zero for gas consumption ... 

In the log for the add on I see the transactions collecting data including gas data 
{'elec_imp': 29883.204, 'watt_now': 1051, 'elec_exp': 2985.099, 'gas_mtr': 4564.756}

The gas data in this record is M3

looking in the statistics_meta database I see this for the sensor:
<html>
<body>


id | statistic_id | source | unit_of_measurement | has_mean | has_sum | name
-- | -- | -- | -- | -- | -- | --
8 | sensor.glow_441793525f6c_gas_meter | recorder | m³ | False | True | NULL

</body>

In there it shows unit of measure m3 which matches the meter record.

**Comment by scooter1556** [comment]
Hi Nigel,

This was meant to be fixed... Is the gas meter sensor updating correctly when new MQTT data comes in?

You could try deleting the Glow device and restarting the addon to get things reconfigured:

![remove_device](https://user-images.githubusercontent.com/964248/185491220-b8a86007-d23a-4638-af48-53fd27aa9e3e.png)

The other information which would be useful is the most recent payload published to MQTT topic:
`homeassistant/sensor/glow_441793525f6c/gas_mtr/config
`

If things aren't populating correctly with the latest code it would be good to see an example of the data coming in from the Glow MQTT broker to understand the issue. I don't have a gas meter so i'm relying entirely on others (and the limited API documentation) to understand the payload.

Many thanks

**Comment by snigehere** [comment]
Ok .. doing this in reverse order as I would prefer not to loose all the history 

This is the mqtt debug which shows all the payload stuff - hope it helps ... I see that in the discovery_data the gas meter config               has "unit_of_measurement": "kWh" ... 
[mqtt-891fb6e1d9f38c3f0fa4235783771462-441793525F6C-7ccaf456fe3c775251283560b3205abc.json.txt](https://github.com/scooter1556/hass-addons/files/9377747/mqtt-891fb6e1d9f38c3f0fa4235783771462-441793525F6C-7ccaf456fe3c775251283560b3205abc.json.txt)

**Comment by snigehere** [comment]
A bit more - This is the sensor - as you can see there is data flowing in and its being added.... 

![gas mtr sensor](https://user-images.githubusercontent.com/104912027/185498889-3c6c0a5c-ee38-464c-95e9-26c507ac343f.jpg)

**Comment by snigehere** [comment]
But on the energy dashboard its zero
![gas mtr sensor energy dashboard](https://user-images.githubusercontent.com/104912027/185499381-e1564c6c-0e40-4e16-a2f2-1a60cf997726.jpg)

**Comment by scooter1556** [comment]
It seems like the addon is attempting to re-configure your gas meter as kWh but things are getting messed up due to retained data from the existing sensor. You mention that the readings you are getting correlate to m3 readings on your meter? I am wondering why the readings are getting classified as kWh in the data from the Glow broker if they are indeed m3...

You could try using something like MQTT Explorer to remove the retained config data in 'homeassistant/sensor/glow_441793525f6c/gas_mtr' and then restart the addon and MQTT integration in Home Assistant:
![remove_topic](https://user-images.githubusercontent.com/964248/185501155-01427d80-8a26-466d-9d0c-3754429355bf.png)

**Comment by snigehere** [comment]
I have now looked at the energy dashboard in a bit more detail ... It looks like that in the past (before the last change) the data from the gas meter was coming in as M3 and passed to the energy dashboard as Kwh .. I didn't look at this in detail in the past as the usage seemed to be consistent ... 

This picture compared the graph from the bright app for the 15th august - it shows the consumption as 5.3 kw ... the energy dashboard shows 0.47kw ... if that read 0.47M3 it would be about correct
![gas mtr sensor energy dashboard 2](https://user-images.githubusercontent.com/104912027/185502138-895e23ae-1306-49b9-91f6-cd1329a81959.jpg)

**Comment by snigehere** [comment]
I need to do some learning on how to use mqtt explorer but have a busy couple of days so will try to have a look after that.

**Comment by snigehere** [comment]
ok - was way easier than I expected!! .. I deleted homeassistant/sensor/glow_441793525f6c/gas_mtr, restarted the add on and it recreated it the same ... still with uom of kWh
{
  "device_class": "energy",
  "state_class": "total_increasing",
  "device": {
    "identifiers": [
      "glow_441793525F6C"
    ],
    "manufacturer": "Glow",
    "name": "441793525F6C"
  },
  "unique_id": "glow_441793525F6C_gas_mtr",
  "name": "glow_441793525F6C_gas_meter",
  "state_topic": "glow/441793525F6C",
  "unit_of_measurement": "kWh",
  "value_template": "{{ value_json.gas_mtr}}"
}
homeassistant

I checked my glow cad and it shows data in kWh .. I checked my supplier cad and it shows the data in m3

from here you can see a match between the number coming from the mqtt record for gas and the M3 number on the supplier cad. 
{
  "elec_imp": 29885.541,
  "watt_now": 729,
  "elec_imp": 29885.543,
  "watt_now": 727,
  "elec_exp": 2985.099,
  "gas_mtr": 4564.756
}

![20220818_232939](https://user-images.githubusercontent.com/104912027/185506956-9534a124-5fb4-45d6-828d-2f48828cc1f9.jpg)

This second picture shows my bright cad with the meter reading in kwh

![20220818_232910](https://user-images.githubusercontent.com/104912027/185506962-5b00e73f-9707-4555-a9c5-2cbeeca21211.jpg)

**Comment by scooter1556** [comment]
That's interesting, I appreciate you working through this with me. It would be very handy to see an example payload you are receiving from the Glowmarkt broker so I can understand why the units are getting detected incorrectly. You can either do this with an MQTT client (like MQTT Explorer) connected to the Glowmarkt broker and subscribed to your device topic or you can use the Python app with the "--debug" flag which will print received payloads to the console: [glow-mqtt](https://github.com/scooter1556/glow-mqtt)

P.S. i'm jealous that export readings work for you. With my SMETS2 meter and Glow CAD I don't get any export readings for some reason. I'm not sure if Glowmarkt need to enable something on their end for the meter to send these. My FIT supplier receive the readings straight from the meter for billing so it must be possible...

**Comment by Twincarb** [comment]
Scot, over on glow2mqtt.py 

if int(data["gasMtr"]["0702"]["03"]["00"], 16) == 0:
gas_units = "m³"
gas_class = "gas" `

elif int(data["gasMtr"]["0702"]["03"]["00"], 16) == 1:
gas_units = "kWh"
gas_class = "energy"

These two lines are the wrong way around, I am showing kWh when it should be m3 and @snigehere is the opposite.

Below would solve this and my issue.
if int(data["gasMtr"]["0702"]["03"]["00"], 16) == 1:
gas_units = "m³"
gas_class = "gas" `

elif int(data["gasMtr"]["0702"]["03"]["00"], 16) == 0:
gas_units = "kWh"
gas_class = "energy"

**Comment by scooter1556** [comment]
@Twincarb, that explains it... oops

Let me get it fixed :)

**Comment by snigehere** [comment]
Thanks @Twincarb and @scooter1556 for working out this issue.  I have installed the fix from Scott and the integration is now working correctly.  My data now shows correctly as m3 and the energy dashboard reflects that.

**Comment by snigehere** [comment]
@scooter1556 Hi Scott - just to chat on the export data - I don't recall doing anything to get it enabled - I am with Octopus and on an SEG tariff rather than FIT (only had my panels for 5 months).  I use Octopus for both my import and export.  Originally, with FIT, smart meters did not exist and so there was no way to get actuals for export.  The process took a quarterly reported generation number and for payments the export was assumed to be 50% of the generation.  My Mum still has this scheme although now, since she has smart meters, she could switch to actuals but there has not been a request from the FIT provider to do this.  Is your fit provider actually using the export data or is it still using the 50% estimation process?   Even though your meter shows export data it will, as far as I understand, only flow to the DDC if the meter is registered with the FIT provider.  

When I look in the glow App I don't see export data - when I asked the glow team they said:

-----------------------------------

We have support for export on our roadmap and have done the work to
pick up the export (and it is great with SMETS2 meters as export is
on by default) - but now have to do the work to add the ability to
store the data and then play it back into our apps, display and APIs.
This work is all done by us as a side activity so it has to fit in
with commercial priorities. So, no, not available yet but we hope to
support it by later this year (time is so strange in Covid that I won't
commit more than that!).

In the meantime, if you have our CAD and can use MQTT, the export feed
is in that automatically.

-----------------------------------

So looking at the last comment it suggests the export data should be there ....

**Comment by scooter1556** [comment]
@snigehere , I am also with Octopus for import but Utility Warehouse for FIT and export. UW do receive actual export readings from the meter to calculate what they owe me on top of the manual generation meter reads for the FIT payments. Given it's a SMETS2 meter I'm not sure why this data isn't available in the data from Glow but maybe there is some complexity in the fact I have different energy providers for import and export...
