### ISSUE TITLE
Mqtt username not passed inside container

### ISSUE THREAD

**Issue by timota** [scooter1556/hass-addons#6]
Hi, 

im recently discovered your addon. It works well when running from docker cmd or natively. But addon has an issue: `mqtt_username` not passed inside container. 

```
00:00:00 python3 -u /glow2mqtt.py --glow_device <REDACTED> --mqtt_address 192.168.1.101 --mqtt_port 1883 --mqtt_username null --mqtt_password <REDACTED> --glow_username <REDACTED> --glow_password <REDACTED> --glow_provider HILD --homeassistant
```
Looks like issue here:

https://github.com/scooter1556/hass-addons/blob/main/glow2mqtt/run.sh#L13

`run.sh` require `mqtt_user`, but option named(webUI) `mqtt_username`

**Comment by scooter1556** [comment]
@timota , great catch! Many thanks for flagging.

Should be fixed now.
