### ISSUE TITLE
Odd issue after 1.2.5 install

### ISSUE THREAD

**Issue by snigehere** [scooter1556/hass-addons#7]
I upgraded to 1.2.5 and this stopped any updates flowing to the energy dashboard .. on investigation the current power value was not being updated (I didnt check others but assume they were the same)
![image](https://user-images.githubusercontent.com/104912027/209537870-99b7266a-889a-4cd0-b497-8bf0b663c340.png)

I restarted the add on but noticed that the configuration showed local as off so turned it back on again and restarted again .. "local" again showed as off (but maybe I failed to save it!)... 

In the log the addon showed connected to the broker but no data was being fetched.

I uninstalled the addon and reinstalled and it all sprung back into life....

Nothing really to add but wanted to record the oddness ....

**Comment by scooter1556** [comment]
@snigehere thanks for reporting.

Not much really changed in the code apart from fixing connections to an MQTT broker which is separate from Home Assistant (i.e. not the MQTT Broker addon). For my setup (broker addon, local mode) the upgrade went OK. Maybe you had some residual MQTT config causing issues with the latest fixes.

I will keep the issue open in case anybody else wants to add anything :)
