### ISSUE TITLE
Getting errors in the log - Template variable warning: 'dict object' has no attribute

### ISSUE THREAD

**Issue by snigehere** [scooter1556/hass-addons#8]
Since uninstalling and re-installing the add on today I am seeing errors in the log every minute .. for example:

2022-12-26 23:59:50.730 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'gas_mtr' when rendering '{{ value_json.gas_mtr}}'
2022-12-26 23:59:50.735 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'watt_now' when rendering '{{ value_json.watt_now}}'
2022-12-26 23:59:50.736 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'elec_imp' when rendering '{{ value_json.elec_imp}}'
2022-12-26 23:59:50.738 WARNING (MainThread) [homeassistant.helpers.template] Template variable warning: 'dict object' has no attribute 'elec_exp' when rendering '{{ value_json.elec_exp}}'

My guess is I have done something when I uninstalled and re-installed but don't know what ... 

As far as I can see my energy data is going to the dashboard - Smart Meter Electricity: Power seems correct and the HA energy dashboard appears to be showing the correct data ...  

Any help would be appreciated.

**Comment by scooter1556** [comment]
Hi @snigehere ,

This isn't generally anything to worry about if data is flowing as expected despite being a bit annoying spamming the logs. It happens when data is received without any relevant data or missing data. I've recently worked around an issue where data packets are sent which don't contain any relevant fields, particularly with older meters. I'm assuming this is some sort of heartbeat type packet but I can't be sure. Previously it was causing the plugin to crash but now we simply get a log message stating that expected data was missing from the payload which is a Home Assistant MQTT expectation more so than a plugin issue.

The plugin still sends data regardless of whether all fields are present because it's not uncommon to get data packets which only include gas readings or only import and not export electricity readings for example. In this instance Home Assistant will warn that some expected fields are missing.

**Comment by snigehere** [comment]
Thanks for the explanation Scott ... but I am not sure that's what's happening here 

Was this a recent change to push the record to the log? 

For me its a bit more than spam ... between 2022-12-27 13:21:18.181 and 2022-12-28 13:21:10.976 .. so just on one day .... I have 34,574 of these messages in the log ... 4 records every 10 seconds .... I hope I am not getting that number of empty records .... 

I am using local mqtt connection to my glow IHD  

I wonder if the mqtt definitions are messed up 

Should I see a comma in the json data?

![image](https://user-images.githubusercontent.com/104912027/209887178-f2d8acd3-7e04-40fd-a0b9-c0feb4ade571.png)

![image](https://user-images.githubusercontent.com/104912027/209884586-7a9088ca-143c-455b-b80e-f0cd9d095065.png)

A bit more .. when I look at the detail of the energy dashboard I see an error message in the configuration but its not stopping the data from being displayed in the dashboard .... most odd

![image](https://user-images.githubusercontent.com/104912027/209887556-ebf15905-a40a-44e2-baaa-e8738ba602dd.png)

![image](https://user-images.githubusercontent.com/104912027/209887532-cdbf5b93-e2f1-4f95-971a-93e8af1c81eb.png)

![image](https://user-images.githubusercontent.com/104912027/209887543-4d210071-7fb2-4f1c-8c09-79d3fbaa8142.png)

**Comment by snigehere** [comment]
I wonder if the mqtt definitions are messed up 
![image](https://user-images.githubusercontent.com/104912027/209884586-7a9088ca-143c-455b-b80e-f0cd9d095065.png)

**Comment by snigehere** [comment]
A bit more .. when I look at the detail of the energy dashboard I see an error message in the configuration but its not stopping the data from being displayed in the dashboard .... most odd

![image](https://user-images.githubusercontent.com/104912027/209887556-ebf15905-a40a-44e2-baaa-e8738ba602dd.png)

![image](https://user-images.githubusercontent.com/104912027/209887532-cdbf5b93-e2f1-4f95-971a-93e8af1c81eb.png)

![image](https://user-images.githubusercontent.com/104912027/209887543-4d210071-7fb2-4f1c-8c09-79d3fbaa8142.png)

**Comment by scooter1556** [comment]
> Was this a recent change to push the record to the log?

This is a Home Assistant MQTT integration warning in the log, not something I have control over.

> Should I see a comma in the json data?

The actual data looks OK to me but it does appear that the local MQTT publishing is doing something weird when you have both gas and electric meters. I can see the timestamps for each meter are different so it must be publishing each meters data separately and I assume every 10 seconds (maybe more). I believe that is different to the behaviour with non-local MQTT.

> A bit more .. when I look at the detail of the energy dashboard I see an error message in the configuration but its not stopping the data from being displayed in the dashboard .... most odd

This is weird... I'd assume when Home Assistant starts the entity isn't initialised with it's last known state from history or MQTT retained data but the energy dashboard requires the entity to be in the recorder list so there should be history which can be loaded on startup... very strange.

I can only think of 2 workarounds to avoid the log messages.

1. Create different sensors for electric and gas meters. Currently the plugin creates a sensor per Glow Device ID and then entities for relevant data fields. This would be significant breaking change.
2. Data caching in the plugin... Store the last value for each entity so we can send the last value if data is missing. This will result in one or two log messages when the plugin first starts and no value is cached but it should minimise log warnings thereafter. There are of course some risks with this method as it adds some additional complexity to the plugin which could make debugging data issues more tricky but it would be less of a breaking change in theory.

**Comment by snigehere** [comment]
thanks - I will leave you to consider if its worth making changes or not ... I guess it will only impact local mqtt users.  I don't recall seeing all these errors in the log in the past but maybe I was focused on them when I was looking at why it didn't work for me after the last update.

Thanks for your continued support.

**Comment by snigehere** [comment]
Just to add an observation ... One result is that the values for the electricity sensors show zero apart from a very tiny bit of time (eg they flash a value then go to zero again) .. I guess that's because of this issue ... but the gas sensor persists the value

![image](https://user-images.githubusercontent.com/104912027/210059397-1b863c4d-0eb8-4a87-8e82-bd224ef8c2a7.png)

![image](https://user-images.githubusercontent.com/104912027/210059406-39d9557b-1f47-4505-8fc5-6140d6000b4a.png)

By taking a video and slowing it down I can just capture the momentary value

![image](https://user-images.githubusercontent.com/104912027/210060864-ba642f31-58f8-4391-92d8-17ff107d5d82.png)

Can the values be cached so they persist until changed or is the empty value causing the value to go to zero?

**Comment by srware** [comment]
> One result is that the values for the electricity sensors show zero apart from a very tiny bit of time (eg they flash a value then go to zero again)

Hmm, this isn't ideal... I would guess this is the default behaviour of the MQTT integration if it receives a payload which is missing entity data, it just sets them to zero although I would find that an odd implementation decision... The plugin code already rejects any readings which are NOT greater than 0 so it can't be the plugin sending zero values. The only thing puzzling me is that I would also expect you to get gas meter readings of zero when electricity data is published but you say these are persisting? Or maybe it's timing and the gas readings are always coming in a few ms after the electricity readings?

Either way I would hope that local caching in the plugin will help this situation for want of a better solution so I will explore this route and see where I end up...

Thanks for your continued debug.

**Comment by scooter1556** [comment]
> One result is that the values for the electricity sensors show zero apart from a very tiny bit of time (eg they flash a value then go to zero again)

Hmm, this isn't ideal... I would guess this is the default behaviour of the MQTT integration if it receives a payload which is missing entity data, it just sets them to zero although I would find that an odd implementation decision... The plugin code already rejects any readings which are NOT greater than 0 so it can't be the plugin sending zero values. The only thing puzzling me is that I would also expect you to get gas meter readings of zero when electricity data is published but you say these are persisting? Or maybe it's timing and the gas readings are always coming in a few ms after the electricity readings?

Either way I would hope that local caching in the plugin will help this situation for want of a better solution so I will explore this route and see where I end up...

Thanks for your continued debug.

**Comment by scooter1556** [comment]
Hi @snigehere , I'm trying to understand a bit more about the data coming in when there are multiple meters in play (gas + electric). I only have electric here so I'm blind in this regard.

Are you able to share some representative MQTT payloads? The main thing I want to understand is whether "gasmeter" is completely omitted from the payload when "electricitymeter" values get updated and vice-versa. I'm concerned this may cause issues with my current dynamic sensor discovery mechanism. It will also help me better decide how to implement caching.

Many thanks.

**Comment by snigehere** [comment]
Let me try 
So in MQTT explorer I see this hierarchy:

glow 
glow/441793525F6C
glow/441793525F6C/SENSOR
glow/441793525F6C/SENSOR/electricitymeter
glow/441793525F6C/SENSOR/gasmeter
glow/441793525F6C/STATE

For the entity glow/441793525F6C I see the electric values followed a fraction of a second later by gas data then a pause for 10 seconds then electric and a fraction later gas etc etc ... 

I took a short video which I hope shows the behaviour

I have also dumped the history from MQTT explorer entities to a text file and also the data from the integration log .. the log mirrors the behaviour I see so a set of electric values then the gas value then just under 10 seconds later it loops again.  The various elements will not quite cover the same time frame as it was running still as I cycled round copying the data but there is a big chunk that will match

I don't know if glow can give any guidance on the expected behaviour - maybe its changed since I started using it ...

I hope this helps - let me know if you need further data ..... 

https://user-images.githubusercontent.com/104912027/210284528-90ce8865-8a16-4811-b470-0c7d0e0dad4b.mp4

[glow mqtt data.txt](https://github.com/scooter1556/hass-addons/files/10333755/glow.mqtt.data.txt)

**Comment by scooter1556** [comment]
Thanks @snigehere , that's definitely helpful.

I would guess in your case the data for both meters is coming in fast enough that the discovery is working OK but I will work on a more robust implementation anyway. It's a bit frustrating that the local MQTT behaviour doesn't more closely mimic what already existed in terms of payload and data publishing but that's life I suppose.

I will keep you posted with progress.

**Comment by snigehere** [comment]
Many thanks Scott

**Comment by snigehere** [comment]
Hi Scott 
Many thanks for your work on this .. I installed the update soon after it was released.  
The log entries are gone, I see the value in my dashboard and have a solid line for the graphs again

![image](https://user-images.githubusercontent.com/104912027/211208034-a9c81497-6fe3-424d-be23-c32fa3c5c61c.png)

![image](https://user-images.githubusercontent.com/104912027/211208043-23105d7a-a903-456a-ae4c-66d2ef9b59ea.png)

Everything else seems to be working OK so I am closing this bug report

**Comment by scooter1556** [comment]
@snigehere pleased to hear everything is working well for you now. It was quite a big overhaul so hopefully there haven't been any additional bugs introduced.

I appreciate the help debugging this one.
